name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write permission to the contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your node version

      - name: Set API secrets
        run: |
          echo "Setting up secrets..."
          echo "REACT_APP_YOUTUBE_API_KEY=${{ secrets.REACT_APP_YOUTUBE_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_GOOGLE_REFRESH_TOKEN=${{ secrets.REACT_APP_GOOGLE_REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_GOOGLE_CLIENT_SECRET=${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "REACT_APP_YOUTUBE_CHANNEL_ID=${{ secrets.REACT_APP_YOUTUBE_CHANNEL_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_GIT_API_KEY=${{ secrets.REACT_APP_GIT_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_GITHUB_TOKEN=${{ secrets.REACT_APP_GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "Secrets are set."

      - name: Show secrets
        run: |
          echo "Printing secrets..."
          echo "REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY" | sed 's/./& /g'
          echo "REACT_APP_GOOGLE_CLIENT_SECRET=$REACT_APP_GOOGLE_CLIENT_SECRET" | sed 's/./& /g'
          echo "REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID" | sed 's/./& /g'
          echo "REACT_APP_YOUTUBE_CHANNEL_ID=$REACT_APP_YOUTUBE_CHANNEL_ID" | sed 's/./& /g'
          echo "REACT_APP_GIT_API_KEY=$REACT_APP_GIT_API_KEY" | sed 's/./& /g'
          echo "REACT_APP_GOOGLE_REFRESH_TOKEN=$REACT_APP_GOOGLE_REFRESH_TOKEN" | sed 's/./& /g'
          echo "REACT_APP_GITHUB_TOKEN=$REACT_APP_GITHUB_TOKEN" | sed 's/./& /g'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          REACT_APP_YOUTUBE_API_KEY: ${{ secrets.REACT_APP_YOUTUBE_API_KEY }}
          REACT_APP_GOOGLE_REFRESH_TOKEN: ${{ secrets.REACT_APP_GOOGLE_REFRESH_TOKEN }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}
          REACT_APP_YOUTUBE_CHANNEL_ID: ${{ secrets.REACT_APP_YOUTUBE_CHANNEL_ID }}
          REACT_APP_GIT_API_KEY: ${{ secrets.REACT_APP_GIT_API_KEY }}
          REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
        run: npm run build

      - name: Create CNAME file
        run: echo 'blog.shilpathota.com' > ./build/CNAME  # Replace with your custom domain

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "blog.shilpathota@gmail.com"
          git config --global user.name "Blog-ShilpaThota"
          git remote set-url origin https://${{ secrets.REACT_APP_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy